sudo: required
language: cpp
dist: trusty

matrix:
  fast_finish: true
  include:
    - compiler: clang
      os: linux
      compiler: clang
      env:
        - COMPILER=clang++-5.0
        - COMPILER_PACKAGE=clang-5.0
    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - COMPILER_PACKAGE=clang

before_install:

install:
  - "export CXX=$COMPILER"
  - "if [ $TRAVIS_OS_NAME = 'linux' ] && [ $COMPILER != 'icpc' ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update -q; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -y --force-yes  $COMPILER_PACKAGE; fi"

script:
  - "$CXX --std=c++11 test.cpp"

